import type { Metadata } from "next";
import { Geist, Geist_Mono,Work_Sans } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import {ThemeProvider} from "../context/ThemeContext"

const workSans = Work_Sans({
   subsets: ["latin"],
  variable: "--body"
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${workSans.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <ThemeProvider>
      <AuthProvider>
      <body className="min-h-full flex flex-col">{children}</body>
      </AuthProvider>
      </ThemeProvider>
    </html>
  );
}
